quarkus:
  http:
    cors:
      ~: true
      origins: /.*/
    auth:
      proactive: false
  devservices:
    enabled: ${USE_DEV_SERVICE:false}
  datasource:
    db-kind: postgresql
    username: ${DB_USER:niyo}
    password: ${DB_PASSWORD:niyo@123}
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:niyo}
      min-size: 2
      max-size: 8
  flyway:
    migrate-at-start: true
    locations: db/migration
    baseline-on-migrate: true
    baseline-version: 1.0.0
  swagger-ui:
    theme: material
    always-include: ${INCLUDE_DOCS:true}
  hibernate-orm:
    database:
      generation:
        ~: validate
  native:
    resources:
      includes: publicKey.pem

# General settings (Dev)
"%dev":
  quarkus:
    log:
      level: INFO
# General settings (Test)
"%test":
  quarkus:
    log:
      level : INFO
    hibernate-orm:
      database:
        generation: drop-and-create
    flyway:
      migrate-at-start: false
    datasource:
      db-kind: h2
      username: ${DB_USER:postgres}
      password: ${DB_PASS:password}
      jdbc:
        url: jdbc:h2:mem:test
        min-size: 3
        max-size: 13

jwt:
  issuer: niyo

mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
    issuer: ${SERVER_URL:http://localhost:8080/api}

smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem

context:
  path: ${SERVER_URL:http://localhost:8080/api}
